IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score, recall_score,f1_score,roc_curve, roc_auc_score
from sklearn import svm
import csv

In [2]:
np.random.seed(187)

LOAD DATA

In [3]:
df = pd.read_csv('Train.csv')

In [4]:
df.head()

,ID,lon,lat,label,VH_01,VV_01,blue_01,green_01,nir_01,nira_01,...,blue_12,green_12,nir_12,nira_12,re1_12,re2_12,re3_12,red_12,swir1_12,swir2_12
0,ID_TR_XAJI0Y,48.203643,40.090329,0,-23.328630,-16.733172,1599,1897,4129,4075,...,1453,1720,3115,2754,2134,2452,2596,1772,3063,2569
1,ID_TR_6DPBHS,49.022098,39.829817,0,-18.638613,-10.334208,1907,2090,2953,3059,...,1930,2282,3508,3377,2831,3019,3097,2662,3470,2642
2,ID_TR_AHXTHV,48.752963,39.764330,0,-21.356376,-14.257931,1355,1719,6722,6528,...,1444,1770,4648,4575,2311,4207,4437,1493,3235,2304
3,ID_TR_3A3ZMF,48.788806,39.770708,0,-20.289892,-9.187885,1504,1657,2093,2040,...,1446,1534,2212,2187,1762,1856,1984,1718,2858,2456
4,ID_TR_8MDD4V,48.195468,39.857486,0,-19.046569,-14.159119,1357,1740,4905,4796,...,1237,1434,2781,2867,1888,2540,2713,1421,2583,1972

In [ ]:
#print(df.head(10))

EDA and STATS:  Done in R, ande in Python too

PREPROCESSING

In [5]:
df1 = df.drop(['lon', 'lat'], axis=1)

In [6]:
df1.head()

,ID,label,VH_01,VV_01,blue_01,green_01,nir_01,nira_01,re1_01,re2_01,...,blue_12,green_12,nir_12,nira_12,re1_12,re2_12,re3_12,red_12,swir1_12,swir2_12
0,ID_TR_XAJI0Y,0,-23.328630,-16.733172,1599,1897,4129,4075,2456,3594,...,1453,1720,3115,2754,2134,2452,2596,1772,3063,2569
1,ID_TR_6DPBHS,0,-18.638613,-10.334208,1907,2090,2953,3059,2662,2777,...,1930,2282,3508,3377,2831,3019,3097,2662,3470,2642
2,ID_TR_AHXTHV,0,-21.356376,-14.257931,1355,1719,6722,6528,2324,5405,...,1444,1770,4648,4575,2311,4207,4437,1493,3235,2304
3,ID_TR_3A3ZMF,0,-20.289892,-9.187885,1504,1657,2093,2040,1902,1914,...,1446,1534,2212,2187,1762,1856,1984,1718,2858,2456
4,ID_TR_8MDD4V,0,-19.046569,-14.159119,1357,1740,4905,4796,2409,4150,...,1237,1434,2781,2867,1888,2540,2713,1421,2583,1972

MORE EDA FIRST

In [7]:
#determine variable types
df1.dtypes

ID              str
label         int64
VH_01       float64
VV_01       float64
blue_01       int64
             ...
re2_12        int64
re3_12        int64
red_12        int64
swir1_12      int64
swir2_12      int64
Length: 146, dtype: object

In [8]:
#change label to category (same as factor in R)
df1['label']= df1['label'].astype("category")

In [9]:
df1.dtypes

ID               str
label       category
VH_01        float64
VV_01        float64
blue_01        int64
              ...
re2_12         int64
re3_12         int64
red_12         int64
swir1_12       int64
swir2_12       int64
Length: 146, dtype: object

## Propsed Steps from here:
 Train Test Split of Train.csv

 StandardScaler on this 'train' data

 PCA on Scaled

 Modeling with this PCA

 Confusion Matrix/F1Score/AUC of model

 Run Model on this 'test' data

 Check multiple model types

 Then run on Test.csv and submit!

BACK TO PREPROCESSING

In [ ]:
#Train Test Split on df1

In [10]:
#first define
X = df1.drop(['label'], axis=1)
y = df1['label']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=187)

In [12]:
# except label, take all columns
cols = X_train.columns.difference(['ID', 'label'])

In [13]:
#STANDARDSCALER

sc = StandardScaler()

# normalise only selected columns
X_train[cols] = sc.fit_transform(X_train[cols])

In [14]:
print(X_train)

               ID     VH_01     VV_01   blue_01  green_01    nir_01   nira_01  \
410  ID_TR_K9QM3P  0.391338  0.459898  0.538248  0.177820  0.345993  0.451430
819  ID_TR_NN16UX  0.076397  1.136580  1.728600  1.652411  0.820518  0.797256
888  ID_TR_SQ0P82  0.742511  0.475065  0.977589  0.664522  0.238576  0.187045
10   ID_TR_9XUY41  0.667970  0.039622  0.061357  0.186511  1.524043  1.717883
221  ID_TR_NF313F  0.598050  0.652943 -0.073825 -0.329162  0.530137  0.616671
..            ...       ...       ...       ...       ...       ...       ...
650  ID_TR_RMHRCN  0.012720  0.610762  1.319299  1.855203  1.534667  1.558544
79   ID_TR_P6VZ41 -0.637186 -0.628189 -0.468106 -0.442146  0.791008  0.800797
466  ID_TR_OT8HLJ -0.596981 -2.020168 -1.189076 -0.876701 -0.721098 -0.974363
286  ID_TR_9V20YA -0.626076  0.592615 -0.791040 -0.824555 -0.267820 -0.057276
619  ID_TR_Q6WW8Y  1.737251  1.395407 -0.528186 -0.456631 -0.004589 -0.083242

       re1_01    re2_01    re3_01  ...   blue_12  green_12    nir_12  \
410  0.330642  0.260677  0.296354  ...  0.226516 -0.327968  0.184060
819  1.403706  0.973281  0.763673  ...  1.941774  2.238374  1.340733
888  0.428580  0.232229  0.242834  ...  0.457683  0.160195  0.143236
10   1.361124  1.512357  1.659151  ... -0.018521  0.017233  1.363866
221  0.038955  0.381578  0.475188  ... -0.531711 -0.767315  0.088805
..        ...       ...       ...  ...       ...       ...       ...
650  2.206375  1.667394  1.610853  ...  1.396220  1.858304  1.355701
79  -0.016401  0.559373  0.655328  ...  0.032336 -0.132703  0.373210
466 -0.329378 -0.437704 -0.566490  ... -1.077265 -0.955606 -1.085558
286 -0.397509 -0.210126 -0.164439  ...  0.212646 -0.094347  0.612709
619 -0.282538 -0.094914 -0.110919  ... -0.069378  0.610002 -0.149334

      nira_12    re1_12    re2_12    re3_12    red_12  swir1_12  swir2_12
410  0.239101  0.046187  0.135084  0.144284  0.213865  0.623607  0.770850
819  1.359082  2.139023  1.674850  1.498335  1.710138  0.935100  0.651655
888  0.247139  0.262863  0.218892  0.182192  0.428974  0.021310  0.231564
10   1.657832  1.132116  1.372484  1.458911  0.818068  2.138543  1.865410
221  0.133265 -0.224021 -0.045678  0.036627  0.172741  0.852341  0.956910
..        ...       ...       ...       ...       ...       ...       ...
650  1.270662  2.358248  1.589399  1.501368  1.865143 -0.279838 -0.559194
79   0.476226  0.339337  0.370075  0.394473  0.334073  1.062685  1.499103
466 -1.124703 -0.552859 -0.896904 -0.968676 -1.178016 -1.189030 -1.158076
286  0.632970  0.260314  0.619856  0.565814  0.428974  0.937399  1.003426
619 -0.073047  0.533071  0.052919  0.045725 -0.055021 -0.301677 -0.458895

[674 rows x 145 columns]

PCA on X_train (and save for re-use on X_test)

In [ ]:
#start with test train split

#X= df1.drop['label']
#y=df1['label']

#need to make sure i get the variables to include in X and y correc, what about ID?

In [ ]:
#X_train, X_test,
#y_train, y_test = train_test_split(X,y ,
#                                   random_state=104,
#                                   test_size=0.25,
#                                   shuffle=True)

PCA on X_TRAIN only

In [15]:
cols2 = X_train.columns.difference(['ID'])

In [16]:
pca = PCA(n_components=10)

In [17]:
components_train = pca.fit_transform(X_train[cols2])

In [18]:
#principals = pd.DataFrame(data = components_train
#             , columns = ['pc1', 'pc2','pc3'])

principals = pd.DataFrame(data = components_train
             , columns = ['pc1', 'pc2','pc3','pc4','pc5','pc6','pc7','pc8','pc9','pc10'])

In [19]:
principals.head(1000)

,pc1,pc2,pc3,pc4,pc5,pc6,pc7,pc8,pc9,pc10
0,9.137606,3.992624,5.313656,1.815054,1.239565,-0.236095,0.678436,-1.902288,0.299220,1.124389
1,0.660523,8.809487,-2.806859,-3.162294,-2.495055,0.428763,-0.450727,1.933679,0.274963,-0.179984
2,-3.120217,3.510732,-4.046220,3.069565,2.526491,-0.616903,1.032870,-2.280891,-1.096935,0.884470
3,11.739705,-4.266337,-2.394055,-5.932022,4.164177,-0.966758,-3.634244,-0.322203,1.883445,-0.828690
4,7.579160,-4.174814,-0.693523,0.917455,-1.275536,0.818160,0.557236,-0.024350,1.024609,0.876682
...,...,...,...,...,...,...,...,...,...,...
669,-5.326057,4.486397,-3.898512,-3.103799,-1.806828,-4.866359,-0.006970,-0.208125,1.823698,0.254405
670,5.441308,1.871607,3.568035,-1.505565,2.868699,-0.383075,-1.532316,-1.162000,0.967816,3.331742
671,-8.777148,-2.666535,2.358829,-0.225779,2.609216,-0.903643,-0.156162,1.981844,1.469950,-0.734358
672,7.632551,-2.605374,0.197421,1.296811,-2.283297,1.637423,-1.426559,-0.005703,-0.275602,3.185529
673,-4.594358,2.039380,-0.508270,-2.721204,-4.162601,-0.212547,0.502353,-0.355193,-0.250389,-0.959995

In [20]:
print('Explained variability per principal component: {}'.format(pca.explained_variance_ratio_))

Explained variability per principal component: [0.48343758 0.1434075  0.0623262  0.05740259 0.04436615 0.02468838
 0.02388025 0.01803921 0.01576423 0.01322479]

In [ ]:
#DO A PLOT OF PCAs:  Do later

## MODEL #1:  NOW TRY A LOGISTIC REGRESSION ON THIS SCALED, PCA'd DATA

In [21]:
clf = LogisticRegression(random_state=0).fit(components_train, y_train)

In [22]:
y_pred = clf.predict(components_train)
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1])

In [23]:
accuracy = accuracy_score(y_train, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.95

In [24]:
clf.score(components_train, y_train)

0.9465875370919882

In [ ]:
#now run Scaler, PCA on X_test --> then test

In [25]:
cols = X_test.columns.difference(['ID', 'label'])

In [26]:
X_test[cols] = sc.transform(X_test[cols])

In [27]:
cols2 = X_test.columns.difference(['ID'])

In [28]:
components_test = pca.transform(X_test[cols2])

In [29]:
y_pred = clf.predict(components_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1])

In [30]:
accuracy = accuracy_score(y_test, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.91

In [31]:
clf.score(components_test, y_test)

0.9100346020761245

In [32]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[157,  13],
       [ 13, 106]])

In [33]:
precision = precision_score(y_test, y_pred)
f"Precision: {round(precision,2)}"

'Precision: 0.89'

In [33]:
recall = recall_score(y_test, y_pred)
f"Recall: {round(recall,2)}"

'Recall: 0.89'

In [34]:
f1 = f1_score(y_test, y_pred)
f"f1 score: {round(f1,2)}"

'f1 score: 0.89'

MODEL #2:  SVM

In [ ]:
#use previous same 'sc' scaler and 'pca' transformations from train!!!

In [35]:
clf = svm.SVC(probability=True)

In [36]:
clf.fit(components_train, y_train)

C:\Users\fikramulla\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

SVC(probability=True)

In [37]:
y_pred = clf.predict(components_train)
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1])

In [38]:
accuracy = accuracy_score(y_train, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.98

In [39]:
clf.score(components_train, y_train)

0.9821958456973294

In [ ]:
#now run on test

In [40]:
y_pred = clf.predict(components_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1])

In [41]:
accuracy = accuracy_score(y_test, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.99

In [42]:
clf.score(components_test, y_test)

0.986159169550173

In [43]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[167,   3],
       [  1, 118]])

In [44]:
precision = precision_score(y_test, y_pred)
f"Precision: {round(precision,2)}"

'Precision: 0.98'

In [45]:
recall = recall_score(y_test, y_pred)
f"Recall: {round(recall,2)}"

'Recall: 0.99'

In [46]:
f1 = f1_score(y_test, y_pred)
f"f1 score: {round(f1,2)}"

'f1 score: 0.98'

In [47]:
#get probability of SVM predictions
probs = clf.predict_proba(components_test)

In [48]:
print(probs)

[[5.72876173e-08 9.99999943e-01]
 [9.94378419e-01 5.62158130e-03]
 [9.94164699e-01 5.83530061e-03]
 [9.93047619e-01 6.95238139e-03]
 [9.89040462e-01 1.09595382e-02]
 [9.92762089e-01 7.23791055e-03]
 [9.86052379e-01 1.39476213e-02]
 [9.29118338e-01 7.08816619e-02]
 [9.74301942e-01 2.56980580e-02]
 [1.47661476e-07 9.99999852e-01]
 [2.39848935e-01 7.60151065e-01]
 [6.20682881e-03 9.93793171e-01]
 [9.77568765e-01 2.24312348e-02]
 [2.26468090e-02 9.77353191e-01]
 [1.14562585e-05 9.99988544e-01]
 [1.85273959e-01 8.14726041e-01]
 [1.16444793e-02 9.88355521e-01]
 [9.92947951e-01 7.05204941e-03]
 [9.93015228e-01 6.98477206e-03]
 [9.66989690e-09 9.99999990e-01]
 [9.92951573e-01 7.04842699e-03]
 [9.88746825e-01 1.12531751e-02]
 [3.69105938e-02 9.63089406e-01]
 [9.93517672e-01 6.48232755e-03]
 [3.83795468e-03 9.96162045e-01]
 [5.19742528e-03 9.94802575e-01]
 [3.99670137e-06 9.99996003e-01]
 [9.97466779e-01 2.53322051e-03]
 [9.93063882e-01 6.93611825e-03]
 [4.06291893e-01 5.93708107e-01]
 [2.53115534e-01 7.46884466e-01]
 [9.94682731e-01 5.31726910e-03]
 [9.84447246e-01 1.55527538e-02]
 [9.85372200e-01 1.46278001e-02]
 [5.85831057e-02 9.41416894e-01]
 [9.91719478e-01 8.28052162e-03]
 [3.01906569e-06 9.99996981e-01]
 [9.92905022e-01 7.09497787e-03]
 [9.92287407e-01 7.71259345e-03]
 [9.97192415e-01 2.80758473e-03]
 [9.75069848e-01 2.49301522e-02]
 [9.92912719e-01 7.08728149e-03]
 [7.82045023e-03 9.92179550e-01]
 [9.72944146e-06 9.99990271e-01]
 [9.97259249e-01 2.74075053e-03]
 [4.44466464e-03 9.95555335e-01]
 [9.63747548e-01 3.62524515e-02]
 [9.95160096e-01 4.83990403e-03]
 [9.68946182e-01 3.10538176e-02]
 [9.94148959e-01 5.85104107e-03]
 [1.88081563e-07 9.99999812e-01]
 [9.99546398e-01 4.53602364e-04]
 [1.16353704e-06 9.99998836e-01]
 [5.85004996e-06 9.99994150e-01]
 [9.95374982e-01 4.62501831e-03]
 [1.27880160e-02 9.87211984e-01]
 [9.95583989e-01 4.41601148e-03]
 [9.96415889e-01 3.58411089e-03]
 [2.40272134e-02 9.75972787e-01]
 [9.93862627e-01 6.13737317e-03]
 [9.91463855e-01 8.53614539e-03]
 [1.96856322e-07 9.99999803e-01]
 [9.93823659e-01 6.17634146e-03]
 [6.63024539e-02 9.33697546e-01]
 [8.72424817e-06 9.99991276e-01]
 [3.90336338e-03 9.96096637e-01]
 [4.17110798e-03 9.95828892e-01]
 [9.87493039e-01 1.25069606e-02]
 [2.32861379e-02 9.76713862e-01]
 [9.96124198e-01 3.87580193e-03]
 [6.64875500e-03 9.93351245e-01]
 [7.09016152e-02 9.29098385e-01]
 [4.54213031e-01 5.45786969e-01]
 [9.55607819e-01 4.43921807e-02]
 [9.72389075e-01 2.76109250e-02]
 [1.66590313e-05 9.99983341e-01]
 [9.91803896e-01 8.19610400e-03]
 [9.98602140e-01 1.39786040e-03]
 [9.97330386e-01 2.66961354e-03]
 [3.54089921e-07 9.99999646e-01]
 [9.96179305e-01 3.82069519e-03]
 [8.67971677e-01 1.32028323e-01]
 [9.91184609e-01 8.81539075e-03]
 [2.89122744e-02 9.71087726e-01]
 [9.97124418e-01 2.87558218e-03]
 [9.94444173e-01 5.55582664e-03]
 [1.85574328e-02 9.81442567e-01]
 [1.03029607e-05 9.99989697e-01]
 [9.89712364e-01 1.02876359e-02]
 [9.40558187e-01 5.94418129e-02]
 [9.95716658e-01 4.28334220e-03]
 [1.27102381e-07 9.99999873e-01]
 [9.83084286e-01 1.69157140e-02]
 [5.85667423e-03 9.94143326e-01]
 [9.97096172e-01 2.90382790e-03]
 [9.92268885e-01 7.73111542e-03]
 [3.13314709e-06 9.99996867e-01]
 [9.97169051e-01 2.83094852e-03]
 [9.95072924e-01 4.92707644e-03]
 [9.93224752e-01 6.77524801e-03]
 [6.64717442e-03 9.93352826e-01]
 [9.85305435e-01 1.46945648e-02]
 [9.95171462e-01 4.82853805e-03]
 [9.72617461e-01 2.73825387e-02]
 [8.01376690e-02 9.19862331e-01]
 [3.64123954e-03 9.96358760e-01]
 [2.47283416e-07 9.99999753e-01]
 [9.79532270e-01 2.04677300e-02]
 [1.08411296e-06 9.99998916e-01]
 [5.99600181e-03 9.94003998e-01]
 [8.98639758e-02 9.10136024e-01]
 [9.83623997e-01 1.63760026e-02]
 [9.97669184e-01 2.33081632e-03]
 [3.36235084e-02 9.66376492e-01]
 [9.94096031e-01 5.90396938e-03]
 [7.95131899e-02 9.20486810e-01]
 [1.28797182e-02 9.87120282e-01]
 [9.93846051e-01 6.15394864e-03]
 [9.79035056e-01 2.09649443e-02]
 [3.31723403e-02 9.66827660e-01]
 [9.90278465e-01 9.72153480e-03]
 [1.29437861e-07 9.99999871e-01]
 [6.15820364e-08 9.99999938e-01]
 [9.94691691e-01 5.30830858e-03]
 [1.27437682e-08 9.99999987e-01]
 [6.51877265e-03 9.93481227e-01]
 [9.76913959e-01 2.30860407e-02]
 [2.50322048e-06 9.99997497e-01]
 [1.51840792e-01 8.48159208e-01]
 [9.83502687e-01 1.64973132e-02]
 [9.96041599e-01 3.95840066e-03]
 [1.12354290e-01 8.87645710e-01]
 [9.89331181e-01 1.06688188e-02]
 [9.86280367e-01 1.37196329e-02]
 [9.94883528e-01 5.11647243e-03]
 [6.61923587e-07 9.99999338e-01]
 [9.93465541e-01 6.53445857e-03]
 [9.08436956e-01 9.15630435e-02]
 [9.92552725e-01 7.44727511e-03]
 [2.18436488e-06 9.99997816e-01]
 [3.17930944e-03 9.96820691e-01]
 [3.80466571e-03 9.96195334e-01]
 [3.10903313e-08 9.99999969e-01]
 [5.50094556e-01 4.49905444e-01]
 [7.49979452e-01 2.50020548e-01]
 [9.95791798e-01 4.20820243e-03]
 [9.91366826e-01 8.63317419e-03]
 [9.96825032e-01 3.17496755e-03]
 [1.03726828e-02 9.89627317e-01]
 [9.87779612e-01 1.22203882e-02]
 [3.79735481e-03 9.96202645e-01]
 [9.96823523e-01 3.17647685e-03]
 [9.89785544e-01 1.02144556e-02]
 [9.24717761e-01 7.52822394e-02]
 [2.94902242e-03 9.97050978e-01]
 [9.94460238e-01 5.53976188e-03]
 [9.94362737e-01 5.63726265e-03]
 [9.90509393e-01 9.49060706e-03]
 [9.96658862e-01 3.34113755e-03]
 [9.91963074e-01 8.03692598e-03]
 [5.83490533e-06 9.99994165e-01]
 [6.01006606e-02 9.39899339e-01]
 [8.65902925e-07 9.99999134e-01]
 [9.95818767e-01 4.18123296e-03]
 [9.91878516e-01 8.12148388e-03]
 [9.51441760e-01 4.85582396e-02]
 [9.96192838e-01 3.80716161e-03]
 [4.65495901e-01 5.34504099e-01]
 [9.95006896e-01 4.99310386e-03]
 [4.24188341e-01 5.75811659e-01]
 [9.95581595e-01 4.41840525e-03]
 [9.95638871e-01 4.36112939e-03]
 [9.97492594e-01 2.50740606e-03]
 [9.96639617e-01 3.36038327e-03]
 [2.91768855e-02 9.70823114e-01]
 [1.00397455e-05 9.99989960e-01]
 [1.69613907e-01 8.30386093e-01]
 [3.34897941e-03 9.96651021e-01]
 [9.94306768e-01 5.69323194e-03]
 [8.05987597e-01 1.94012403e-01]
 [9.94172048e-01 5.82795185e-03]
 [9.96394824e-01 3.60517625e-03]
 [1.06111908e-02 9.89388809e-01]
 [9.95251472e-01 4.74852817e-03]
 [9.93187474e-01 6.81252590e-03]
 [9.92190445e-01 7.80955506e-03]
 [9.86395014e-01 1.36049856e-02]
 [9.92974668e-01 7.02533215e-03]
 [9.71013931e-01 2.89860695e-02]
 [3.15411311e-07 9.99999685e-01]
 [9.82587719e-01 1.74122808e-02]
 [9.43472995e-01 5.65270052e-02]
 [9.93859126e-01 6.14087380e-03]
 [9.97238457e-01 2.76154325e-03]
 [9.71547507e-01 2.84524928e-02]
 [9.87448497e-01 1.25515026e-02]
 [9.98027004e-01 1.97299588e-03]
 [1.22533418e-05 9.99987747e-01]
 [9.72294135e-01 2.77058652e-02]
 [1.94498790e-06 9.99998055e-01]
 [3.99878897e-03 9.96001211e-01]
 [5.21874901e-07 9.99999478e-01]
 [9.89123274e-01 1.08767258e-02]
 [9.70960448e-07 9.99999029e-01]
 [6.98586399e-03 9.93014136e-01]
 [4.74618730e-01 5.25381270e-01]
 [6.08219035e-02 9.39178096e-01]
 [9.92877239e-01 7.12276100e-03]
 [9.79080301e-01 2.09196992e-02]
 [9.33001751e-06 9.99990670e-01]
 [9.94814869e-01 5.18513085e-03]
 [9.94884170e-01 5.11583005e-03]
 [2.02086607e-02 9.79791339e-01]
 [9.91135453e-01 8.86454664e-03]
 [5.29221769e-03 9.94707782e-01]
 [4.13085590e-01 5.86914410e-01]
 [1.60842154e-02 9.83915785e-01]
 [9.52805035e-01 4.71949652e-02]
 [7.74239582e-03 9.92257604e-01]
 [8.70515024e-09 9.99999991e-01]
 [9.93230938e-01 6.76906157e-03]
 [9.92325190e-01 7.67481049e-03]
 [9.93174371e-01 6.82562940e-03]
 [9.92339902e-01 7.66009817e-03]
 [1.10528308e-01 8.89471692e-01]
 [9.93800975e-01 6.19902501e-03]
 [1.18621221e-01 8.81378779e-01]
 [2.91899632e-03 9.97081004e-01]
 [9.42025465e-03 9.90579745e-01]
 [5.42342011e-06 9.99994577e-01]
 [9.98053837e-01 1.94616276e-03]
 [9.90531092e-01 9.46890838e-03]
 [6.65166567e-02 9.33483343e-01]
 [9.96456148e-01 3.54385179e-03]
 [3.65127795e-03 9.96348722e-01]
 [9.12903514e-01 8.70964862e-02]
 [8.98336892e-02 9.10166311e-01]
 [7.21943641e-01 2.78056359e-01]
 [9.50781049e-01 4.92189508e-02]
 [1.45022333e-06 9.99998550e-01]
 [9.94092891e-01 5.90710893e-03]
 [9.95947017e-01 4.05298280e-03]
 [6.60224539e-02 9.33977546e-01]
 [9.94151329e-01 5.84867108e-03]
 [4.78746278e-02 9.52125372e-01]
 [1.66646434e-06 9.99998334e-01]
 [9.77218476e-01 2.27815238e-02]
 [1.27075538e-02 9.87292446e-01]
 [6.42868313e-01 3.57131687e-01]
 [2.48906793e-07 9.99999751e-01]
 [9.96397243e-01 3.60275739e-03]
 [7.63980498e-02 9.23601950e-01]
 [9.61906894e-01 3.80931062e-02]
 [9.93375871e-01 6.62412860e-03]
 [9.90780756e-01 9.21924366e-03]
 [8.51332013e-01 1.48667987e-01]
 [9.21625546e-03 9.90783745e-01]
 [9.98244642e-01 1.75535825e-03]
 [1.54900991e-06 9.99998451e-01]
 [9.87822722e-01 1.21772776e-02]
 [9.73565134e-01 2.64348661e-02]
 [9.95071293e-01 4.92870741e-03]
 [9.95301213e-01 4.69878667e-03]
 [9.76361886e-01 2.36381143e-02]
 [2.58219633e-03 9.97417804e-01]
 [4.29931272e-08 9.99999957e-01]
 [9.63744454e-01 3.62555462e-02]
 [4.33178493e-03 9.95668215e-01]
 [9.94975079e-01 5.02492100e-03]
 [9.97830649e-01 2.16935086e-03]
 [8.51953484e-01 1.48046516e-01]
 [9.90662022e-01 9.33797770e-03]
 [9.84111471e-01 1.58885292e-02]
 [9.90235270e-01 9.76472985e-03]
 [7.95624369e-03 9.92043756e-01]
 [9.87267658e-01 1.27323422e-02]
 [9.92377369e-01 7.62263082e-03]
 [6.91166606e-06 9.99993088e-01]
 [9.91950483e-01 8.04951687e-03]
 [9.93635805e-01 6.36419532e-03]
 [9.93416841e-01 6.58315882e-03]
 [9.94550676e-01 5.44932441e-03]
 [1.35530931e-02 9.86446907e-01]
 [9.67784603e-03 9.90322154e-01]
 [9.08622961e-02 9.09137704e-01]
 [3.88839506e-06 9.99996112e-01]
 [9.92037201e-01 7.96279877e-03]
 [9.95433532e-01 4.56646791e-03]
 [3.24272340e-08 9.99999968e-01]]

In [49]:
print(type(probs))

<class 'numpy.ndarray'>

In [50]:
print(probs.ndim)

2

In [51]:
probsdf = pd.DataFrame(probs, columns=["0", "1"])

In [52]:
probsdf.to_csv("svm_1.csv")

NOW RUN ON SUPPLIED TEST

In [ ]:
#1. sc on Test (transform only)
#2. pca on Test (transform only)
#3. run model on Test (predict only)
#4. run predict_proba on predictions
#5. somehow only select high probability column
#6. export everything to csv's

In [56]:
# trying #5 first to make my life easier
probsdf.head()

              0         1
0  5.728762e-08  1.000000
1  9.943784e-01  0.005622
2  9.941647e-01  0.005835
3  9.930476e-01  0.006952
4  9.890405e-01  0.010960

In [60]:
probsdf['max_val'] = probsdf[['0', '1']].max(axis=1)

In [61]:
probsdf.head()

              0         1   max_val
0  5.728762e-08  1.000000  1.000000
1  9.943784e-01  0.005622  0.994378
2  9.941647e-01  0.005835  0.994165
3  9.930476e-01  0.006952  0.993048
4  9.890405e-01  0.010960  0.989040

In [68]:
probmax = probsdf['max_val']

In [71]:
probmax.head()

0    1.000000
1    0.994378
2    0.994165
3    0.993048
4    0.989040
Name: max_val, dtype: float64

In [74]:
probmax2 = pd.DataFrame(probmax)

In [75]:
probmax2.head()

    max_val
0  1.000000
1  0.994378
2  0.994165
3  0.993048
4  0.989040

In [86]:
#great that worked!, now select the 'max_val' column and append to your prediction dataframe/csv
preddf = pd.DataFrame(y_pred, columns=["pred"])

In [87]:
preddf.head(15)

    pred
0      1
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      1
10     1
11     1
12     0
13     1
14     1

In [88]:
#now combine probmax2 and add it to preddf
final1 = pd.concat([preddf, probmax2], axis=1)

In [89]:
final1.head(15)

    pred   max_val
0      1  1.000000
1      0  0.994378
2      0  0.994165
3      0  0.993048
4      0  0.989040
5      0  0.992762
6      0  0.986052
7      0  0.929118
8      0  0.974302
9      1  1.000000
10     1  0.760151
11     1  0.993793
12     0  0.977569
13     1  0.977353
14     1  0.999989

In [90]:
final1.to_csv("final.csv")

NOW RUN ON SUPPLIED TEST

In [102]:
df = pd.read_csv('Test.csv')

In [103]:
df1 = df.drop(['lon', 'lat'], axis=1)

In [104]:
df1.dtypes

ID              str
VH_01       float64
VV_01       float64
blue_01       int64
green_01      int64
             ...
re2_12        int64
re3_12        int64
red_12        int64
swir1_12      int64
swir2_12      int64
Length: 145, dtype: object

In [105]:
#ok, it only has ID, no problem
cols = df1.columns.difference(['ID'])

In [106]:
df1[cols] = sc.transform(df1[cols])

In [107]:
cols2 = df1.columns.difference(['ID'])

In [108]:
components_test = pca.transform(df1[cols2])

In [109]:
y_pred = clf.predict(components_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [111]:
length = len(y_pred)
print(length)  # Output: 858 is correct for 'Test.csv'

858

In [116]:
preddf = pd.DataFrame(y_pred, columns=["pred"])

In [117]:
preddf.head()

   pred
0     0
1     0
2     0
3     0
4     0

In [112]:
probs = clf.predict_proba(components_test)

In [113]:
print(probs)

[[0.99472065 0.00527935]
 [0.97778904 0.02221096]
 [0.97565295 0.02434705]
 ...
 [0.01054246 0.98945754]
 [0.00447361 0.99552639]
 [0.01909744 0.98090256]]

In [114]:
length = len(probs)
print(length)  # Output: 858 is correct for 'Test.csv'

858

In [115]:
print(probs.ndim)

2

In [118]:
probsdf = pd.DataFrame(probs, columns=["0", "1"])

In [119]:
probsdf.head()

          0         1
0  0.994721  0.005279
1  0.977789  0.022211
2  0.975653  0.024347
3  0.995554  0.004446
4  0.956689  0.043311

In [120]:
probsdf['max_val'] = probsdf[['0', '1']].max(axis=1)
probsdf.head()

          0         1   max_val
0  0.994721  0.005279  0.994721
1  0.977789  0.022211  0.977789
2  0.975653  0.024347  0.975653
3  0.995554  0.004446  0.995554
4  0.956689  0.043311  0.956689

In [121]:
probmax = probsdf['max_val']

In [122]:
probmax2 = pd.DataFrame(probmax)

In [123]:
probmax2.head()

    max_val
0  0.994721
1  0.977789
2  0.975653
3  0.995554
4  0.956689

In [124]:
#now combine probmax2 and add it to preddf
model1 = pd.concat([preddf, probmax2], axis=1)

In [125]:
model1.head(15)

    pred   max_val
0      0  0.994721
1      0  0.977789
2      0  0.975653
3      0  0.995554
4      0  0.956689
5      0  0.890516
6      0  0.875861
7      0  0.703337
8      0  0.988236
9      0  0.964649
10     0  0.992550
11     0  0.990002
12     0  0.989051
13     0  0.990142
14     0  0.990861

In [126]:
model1.to_csv("model1_svm.csv")