IMPORT LIBRARIES

In [303]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score, recall_score,f1_score,roc_curve, roc_auc_score
from sklearn import svm
import csv

In [304]:
np.random.seed(187)

LOAD DATA

In [305]:
df = pd.read_csv('Train.csv')

In [225]:
df.head()

,ID,lon,lat,label,VH_01,VV_01,blue_01,green_01,nir_01,nira_01,...,blue_12,green_12,nir_12,nira_12,re1_12,re2_12,re3_12,red_12,swir1_12,swir2_12
0,ID_TR_XAJI0Y,48.203643,40.090329,0,-23.328630,-16.733172,1599,1897,4129,4075,...,1453,1720,3115,2754,2134,2452,2596,1772,3063,2569
1,ID_TR_6DPBHS,49.022098,39.829817,0,-18.638613,-10.334208,1907,2090,2953,3059,...,1930,2282,3508,3377,2831,3019,3097,2662,3470,2642
2,ID_TR_AHXTHV,48.752963,39.764330,0,-21.356376,-14.257931,1355,1719,6722,6528,...,1444,1770,4648,4575,2311,4207,4437,1493,3235,2304
3,ID_TR_3A3ZMF,48.788806,39.770708,0,-20.289892,-9.187885,1504,1657,2093,2040,...,1446,1534,2212,2187,1762,1856,1984,1718,2858,2456
4,ID_TR_8MDD4V,48.195468,39.857486,0,-19.046569,-14.159119,1357,1740,4905,4796,...,1237,1434,2781,2867,1888,2540,2713,1421,2583,1972

In [226]:
#print(df.head(10))

EDA and STATS:  Done in R, ande in Python too

PREPROCESSING

In [306]:
df1 = df.drop(['lon', 'lat'], axis=1)

In [228]:
df1.head()

,ID,label,VH_01,VV_01,blue_01,green_01,nir_01,nira_01,re1_01,re2_01,...,blue_12,green_12,nir_12,nira_12,re1_12,re2_12,re3_12,red_12,swir1_12,swir2_12
0,ID_TR_XAJI0Y,0,-23.328630,-16.733172,1599,1897,4129,4075,2456,3594,...,1453,1720,3115,2754,2134,2452,2596,1772,3063,2569
1,ID_TR_6DPBHS,0,-18.638613,-10.334208,1907,2090,2953,3059,2662,2777,...,1930,2282,3508,3377,2831,3019,3097,2662,3470,2642
2,ID_TR_AHXTHV,0,-21.356376,-14.257931,1355,1719,6722,6528,2324,5405,...,1444,1770,4648,4575,2311,4207,4437,1493,3235,2304
3,ID_TR_3A3ZMF,0,-20.289892,-9.187885,1504,1657,2093,2040,1902,1914,...,1446,1534,2212,2187,1762,1856,1984,1718,2858,2456
4,ID_TR_8MDD4V,0,-19.046569,-14.159119,1357,1740,4905,4796,2409,4150,...,1237,1434,2781,2867,1888,2540,2713,1421,2583,1972

MORE EDA FIRST

In [229]:
#determine variable types
df1.dtypes

ID              str
label         int64
VH_01       float64
VV_01       float64
blue_01       int64
             ...
re2_12        int64
re3_12        int64
red_12        int64
swir1_12      int64
swir2_12      int64
Length: 146, dtype: object

In [307]:
#change label to category (same as factor in R)
df1['label']= df1['label'].astype("category")

In [308]:
df1.dtypes

ID               str
label       category
VH_01        float64
VV_01        float64
blue_01        int64
              ...
re2_12         int64
re3_12         int64
red_12         int64
swir1_12       int64
swir2_12       int64
Length: 146, dtype: object

## Propsed Steps from here:
 Train Test Split of Train.csv

 StandardScaler on this 'train' data

 PCA on Scaled

 Modeling with this PCA

 Confusion Matrix/F1Score/AUC of model

 Run Model on this 'test' data

 Check multiple model types

 Then run on Test.csv and submit!

BACK TO PREPROCESSING

In [ ]:
#Train Test Split on df1

In [309]:
#first define
X = df1.drop(['label'], axis=1)
y = df1['label']

In [310]:
#Changed test_size to 'None'
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=None, random_state=187)

In [311]:
# except label, take all columns
cols = X_train.columns.difference(['ID', 'label'])

In [312]:
#STANDARDSCALER

sc = StandardScaler()

# normalise only selected columns
X_train[cols] = sc.fit_transform(X_train[cols])

In [313]:
print(X_train)

               ID     VH_01     VV_01   blue_01  green_01    nir_01   nira_01  \
452  ID_TR_4T60PL -1.103139 -1.677825 -0.943514 -1.040636 -1.162400 -1.209931
482  ID_TR_XJ37C9 -0.430000  0.198043  0.856687  0.750678  0.454522  0.424746
116  ID_TR_X7PTX6  1.226559  1.035255  0.001970 -0.077658  0.212103  0.581904
864  ID_TR_D32LX2 -1.589752 -1.168219  0.977709  0.326265 -0.683533 -0.727743
826  ID_TR_4K7BPG  0.111961  0.452741  1.083603  1.005326  0.499901  0.435462
..            ...       ...       ...       ...       ...       ...       ...
650  ID_TR_RMHRCN  0.011811  0.611885  1.321865  1.871713  1.556751  1.573664
79   ID_TR_P6VZ41 -0.634322 -0.622814 -0.478336 -0.449385  0.804417  0.809306
466  ID_TR_OT8HLJ -0.594349 -2.010015 -1.204468 -0.888433 -0.725330 -0.981338
286  ID_TR_9V20YA -0.623276  0.593801 -0.803583 -0.835747 -0.266764 -0.056251
619  ID_TR_Q6WW8Y  1.726328  1.393837 -0.538847 -0.464020 -0.000461 -0.082444

       re1_01    re2_01    re3_01  ...   blue_12  green_12    nir_12  \
452 -1.682311 -1.309134 -1.285328  ... -1.352800 -1.497239 -1.310808
482  0.752291  0.542000  0.487315  ...  2.328599  2.548317  1.933106
116  0.149540  0.454329  0.463556  ... -0.399212 -0.546568  0.582276
864 -0.348106 -0.632206 -0.633291  ... -0.114970 -0.577794 -0.879750
826  0.865978  0.471576  0.422639  ...  0.095920  0.199396 -1.128226
..        ...       ...       ...  ...       ...       ...       ...
650  2.219488  1.687461  1.631679  ...  1.365842  1.840518  1.368887
79  -0.019917  0.567869  0.665503  ...  0.013398 -0.140625  0.377730
466 -0.335236 -0.439619 -0.569936  ... -1.086896 -0.959451 -1.093906
286 -0.403876 -0.209664 -0.163402  ...  0.192196 -0.102459  0.619341
619 -0.288045 -0.093250 -0.109286  ... -0.087462  0.598401 -0.149424

      nira_12    re1_12    re2_12    re3_12    red_12  swir1_12  swir2_12
452 -1.283354 -1.771083 -1.352065 -1.353003 -1.693009 -1.190095 -1.162813
482  1.782774  2.694997  2.153421  2.050532  1.881213 -0.315459 -0.629688
116  0.941409  0.070441  0.593770  0.686059  0.339020  1.098210  1.017623
864 -0.944920 -0.707488 -0.793507 -0.825264 -0.669094 -1.134928 -1.119233
826 -1.148520 -0.707488 -1.071957 -1.071542 -0.653293 -1.134928 -1.106159
..        ...       ...       ...       ...       ...       ...       ...
650  1.278494  2.355769  1.603151  1.515144  1.849611 -0.282129 -0.562866
79   0.478928  0.335703  0.373330  0.398479  0.320059  1.060282  1.494094
466 -1.132339 -0.557003 -0.904556 -0.976702 -1.190532 -1.191245 -1.161360
286  0.636684  0.256634  0.625261  0.571333  0.414866  0.935006  0.998739
619 -0.073892  0.529547  0.053444  0.046653 -0.068650 -0.303966 -0.462633

[722 rows x 145 columns]

PCA on X_train (and save for re-use on X_test)

In [ ]:
#start with test train split

#X= df1.drop['label']
#y=df1['label']

#need to make sure i get the variables to include in X and y correc, what about ID?

In [ ]:
#X_train, X_test,
#y_train, y_test = train_test_split(X,y ,
#                                   random_state=104,
#                                   test_size=0.25,
#                                   shuffle=True)

PCA on X_TRAIN only

In [314]:
cols2 = X_train.columns.difference(['ID'])

In [315]:
pca = PCA(n_components=20)

In [316]:
components_train = pca.fit_transform(X_train[cols2])

In [317]:
#principals = pd.DataFrame(data = components_train
#             , columns = ['pc1', 'pc2','pc3'])

principals = pd.DataFrame(data = components_train
             , columns = ['pc1', 'pc2','pc3','pc4','pc5','pc6','pc7','pc8','pc9','pc10', 'pc11', 'pc12','pc13','pc14','pc15','pc16','pc17','pc18','pc19','pc20'])

In [318]:
principals.head(1000)

,pc1,pc2,pc3,pc4,pc5,pc6,pc7,pc8,pc9,pc10,pc11,pc12,pc13,pc14,pc15,pc16,pc17,pc18,pc19,pc20
0,-14.696327,-6.265170,-0.363836,-0.867818,0.967680,0.047057,-0.427232,-0.608422,0.853882,1.768926,0.249773,-1.523557,0.769761,-0.495847,-0.047358,-0.603222,-0.386922,-0.237875,0.140223,-0.133721
1,2.163371,8.344093,1.716784,-7.259704,-4.058077,5.127921,-5.790070,1.369829,2.265012,-1.091152,0.195987,4.482638,-0.570111,0.004607,2.214177,1.284038,3.359767,-2.094154,0.590269,-1.270359
2,10.400029,-4.292985,-1.270526,2.028634,-2.467309,-1.161052,-1.337716,-1.188531,0.967874,-0.571780,-0.196629,0.080701,-0.786913,-0.342331,-0.387412,0.321515,0.556411,-0.613328,0.415597,0.436420
3,-4.363045,4.065335,4.406607,-1.704145,-4.574089,1.359443,-0.732663,0.129210,-0.225847,-1.903653,1.291192,-3.205233,0.738459,0.371082,-1.078695,0.788351,-0.136350,0.011619,-1.212787,0.732969
4,-3.492664,4.006611,-3.097932,-0.142786,1.446309,2.803156,1.284381,-2.307215,-1.232884,-1.438142,1.227865,-1.359600,-0.358226,2.017755,0.226395,1.213463,-0.825011,1.235686,0.200067,-0.209157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
717,-5.356157,4.424793,-3.699849,-3.329041,-1.805529,-4.847155,-0.507619,-0.685449,1.882996,0.225014,-0.133364,0.962470,-0.443604,1.561426,-1.201471,0.096993,-0.278202,0.134044,0.172986,-1.884625
718,5.392905,1.932205,3.658904,-1.201576,3.034332,-0.238379,-1.320175,-1.508095,0.669331,3.374902,0.528126,-1.282104,0.003300,-0.275132,0.815704,0.295450,-0.219683,-0.433149,0.133936,0.478540
719,-8.795555,-2.691869,2.279473,0.042853,2.684758,-0.875406,-0.455825,1.755133,1.759088,-0.772232,1.052722,0.448115,-0.757693,1.948791,0.888632,-0.867718,1.034013,0.218039,-0.825504,-0.881885
720,7.573139,-2.550383,0.275691,1.134986,-2.272887,1.757405,-1.129780,-0.005655,-0.418598,3.348998,-1.209102,-0.158084,0.311013,0.054166,1.331766,-0.186395,0.491030,-1.193839,-1.624813,-0.767806
721,-4.666065,2.001421,-0.183760,-2.831127,-4.071905,-0.376859,0.621275,-0.322481,-0.277372,-1.015795,0.580630,-1.791737,-0.390003,-1.143049,0.686596,1.016884,0.396326,-1.269487,-0.405341,-0.326880

In [319]:
print('Explained variability per principal component: {}'.format(pca.explained_variance_ratio_))

Explained variability per principal component: [0.48329017 0.14279037 0.06147777 0.05819935 0.0446613  0.02455194
 0.02407878 0.01819871 0.01576678 0.01317331 0.01123447 0.01050298
 0.0075812  0.00700027 0.00644733 0.00551921 0.00465591 0.00388717
 0.00383491 0.00333597]

In [ ]:
#DO A PLOT OF PCAs:  Do later

## MODEL #1:  NOW TRY A LOGISTIC REGRESSION ON THIS SCALED, PCA'd DATA

In [243]:
clf = LogisticRegression(random_state=0).fit(components_train, y_train)

In [244]:
y_pred = clf.predict(components_train)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1])

In [245]:
accuracy = accuracy_score(y_train, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.98

In [246]:
clf.score(components_train, y_train)

0.9778393351800554

In [ ]:
#now run Scaler, PCA on X_test --> then test

In [247]:
cols = X_test.columns.difference(['ID', 'label'])

In [248]:
X_test[cols] = sc.transform(X_test[cols])

In [249]:
cols2 = X_test.columns.difference(['ID'])

In [250]:
components_test = pca.transform(X_test[cols2])

In [251]:
y_pred = clf.predict(components_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0])

In [252]:
accuracy = accuracy_score(y_test, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.96

In [253]:
clf.score(components_test, y_test)

0.9585062240663901

In [254]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[135,   4],
       [  6,  96]])

In [255]:
precision = precision_score(y_test, y_pred)
f"Precision: {round(precision,2)}"

'Precision: 0.96'

In [256]:
recall = recall_score(y_test, y_pred)
f"Recall: {round(recall,2)}"

'Recall: 0.94'

In [257]:
f1 = f1_score(y_test, y_pred)
f"f1 score: {round(f1,2)}"

'f1 score: 0.95'

## MODEL #2:  SVM

In [ ]:
#use previous same 'sc' scaler and 'pca' transformations from train!!!

In [258]:
clf = svm.SVC(probability=True)

In [259]:
clf.fit(components_train, y_train)

C:\Users\fikramulla\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

SVC(probability=True)

In [260]:
y_pred = clf.predict(components_train)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1])

In [261]:
accuracy = accuracy_score(y_train, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.99

In [262]:
clf.score(components_train, y_train)

0.9889196675900277

In [209]:
#now run on test

In [263]:
y_pred = clf.predict(components_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0])

In [264]:
accuracy = accuracy_score(y_test, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.99

In [265]:
clf.score(components_test, y_test)

0.991701244813278

In [266]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[137,   2],
       [  0, 102]])

In [267]:
precision = precision_score(y_test, y_pred)
f"Precision: {round(precision,2)}"

'Precision: 0.98'

In [268]:
recall = recall_score(y_test, y_pred)
f"Recall: {round(recall,2)}"

'Recall: 1.0'

In [269]:
f1 = f1_score(y_test, y_pred)
f"f1 score: {round(f1,2)}"

'f1 score: 0.99'

In [270]:
#get probability of SVM predictions
probs = clf.predict_proba(components_test)

In [271]:
print(probs)

[[1.16386463e-08 9.99999988e-01]
 [9.97147262e-01 2.85273814e-03]
 [9.96946907e-01 3.05309331e-03]
 [9.92302116e-01 7.69788415e-03]
 [9.89264875e-01 1.07351247e-02]
 [9.93502215e-01 6.49778537e-03]
 [9.92116446e-01 7.88355384e-03]
 [9.92387966e-01 7.61203360e-03]
 [9.73663756e-01 2.63362441e-02]
 [7.60640340e-08 9.99999924e-01]
 [7.52665141e-02 9.24733486e-01]
 [7.49504295e-03 9.92504957e-01]
 [9.84862842e-01 1.51371575e-02]
 [5.42518229e-02 9.45748177e-01]
 [1.30515018e-07 9.99999869e-01]
 [8.06163631e-03 9.91938364e-01]
 [2.76941531e-03 9.97230585e-01]
 [9.95045602e-01 4.95439767e-03]
 [9.92531790e-01 7.46821023e-03]
 [2.35445553e-07 9.99999765e-01]
 [9.91477664e-01 8.52233579e-03]
 [9.88450470e-01 1.15495304e-02]
 [7.77565990e-03 9.92224340e-01]
 [9.90155333e-01 9.84466744e-03]
 [1.09492833e-05 9.99989051e-01]
 [1.87152897e-02 9.81284710e-01]
 [4.97653197e-07 9.99999502e-01]
 [9.98318406e-01 1.68159423e-03]
 [9.94319820e-01 5.68017972e-03]
 [3.34100389e-01 6.65899611e-01]
 [2.66419019e-02 9.73358098e-01]
 [9.94987787e-01 5.01221347e-03]
 [9.82701087e-01 1.72989134e-02]
 [9.88519942e-01 1.14800582e-02]
 [2.67506846e-02 9.73249315e-01]
 [9.91255113e-01 8.74488720e-03]
 [1.21117371e-05 9.99987888e-01]
 [9.81877044e-01 1.81229557e-02]
 [9.94258867e-01 5.74113277e-03]
 [9.97918662e-01 2.08133760e-03]
 [9.79709559e-01 2.02904414e-02]
 [9.92183956e-01 7.81604447e-03]
 [4.84373373e-03 9.95156266e-01]
 [1.52804140e-06 9.99998472e-01]
 [9.89581992e-01 1.04180081e-02]
 [1.29523774e-02 9.87047623e-01]
 [9.77782833e-01 2.22171667e-02]
 [9.95629943e-01 4.37005715e-03]
 [9.54975328e-01 4.50246715e-02]
 [9.94949722e-01 5.05027751e-03]
 [1.80115110e-07 9.99999820e-01]
 [9.98973036e-01 1.02696435e-03]
 [4.09947559e-08 9.99999959e-01]
 [3.63987801e-06 9.99996360e-01]
 [9.94908115e-01 5.09188534e-03]
 [3.57669696e-03 9.96423303e-01]
 [9.96442877e-01 3.55712271e-03]
 [9.97688702e-01 2.31129830e-03]
 [6.63193352e-03 9.93368066e-01]
 [9.96474648e-01 3.52535210e-03]
 [9.95115912e-01 4.88408780e-03]
 [1.40522262e-06 9.99998595e-01]
 [9.93290361e-01 6.70963871e-03]
 [2.92355540e-02 9.70764446e-01]
 [3.47642848e-06 9.99996524e-01]
 [1.54216690e-05 9.99984578e-01]
 [1.04015287e-05 9.99989598e-01]
 [9.84323785e-01 1.56762153e-02]
 [1.11898033e-02 9.88810197e-01]
 [9.96336624e-01 3.66337565e-03]
 [4.85130463e-03 9.95148695e-01]
 [3.97623178e-02 9.60237682e-01]
 [8.38548521e-01 1.61451479e-01]
 [9.64103956e-01 3.58960438e-02]
 [3.92328469e-01 6.07671531e-01]
 [2.86214833e-02 9.71378517e-01]
 [9.93074849e-01 6.92515088e-03]
 [9.98804839e-01 1.19516121e-03]
 [9.98301466e-01 1.69853396e-03]
 [1.50412946e-07 9.99999850e-01]
 [9.98354463e-01 1.64553707e-03]
 [9.76568499e-01 2.34315008e-02]
 [9.91392071e-01 8.60792873e-03]
 [4.40676743e-03 9.95593233e-01]
 [9.95676900e-01 4.32310009e-03]
 [9.95501070e-01 4.49893024e-03]
 [2.90935610e-02 9.70906439e-01]
 [2.81203867e-03 9.97187961e-01]
 [9.86805409e-01 1.31945909e-02]
 [9.70902978e-01 2.90970215e-02]
 [9.97512582e-01 2.48741845e-03]
 [1.27781873e-07 9.99999872e-01]
 [9.87277270e-01 1.27227301e-02]
 [1.01843456e-06 9.99998982e-01]
 [9.97791654e-01 2.20834554e-03]
 [9.90563758e-01 9.43624195e-03]
 [1.91267498e-06 9.99998087e-01]
 [9.95337026e-01 4.66297417e-03]
 [9.97925323e-01 2.07467726e-03]
 [9.95045635e-01 4.95436479e-03]
 [3.13219019e-06 9.99996868e-01]
 [9.84788573e-01 1.52114266e-02]
 [9.96178208e-01 3.82179186e-03]
 [9.78324910e-01 2.16750905e-02]
 [6.84565234e-02 9.31543477e-01]
 [8.12684718e-06 9.99991873e-01]
 [5.12973991e-08 9.99999949e-01]
 [9.79085074e-01 2.09149264e-02]
 [4.05693501e-07 9.99999594e-01]
 [4.78135519e-03 9.95218645e-01]
 [3.10024630e-02 9.68997537e-01]
 [9.71604072e-01 2.83959275e-02]
 [9.97917122e-01 2.08287806e-03]
 [1.36447073e-06 9.99998636e-01]
 [9.93884308e-01 6.11569206e-03]
 [7.24721773e-03 9.92752782e-01]
 [2.00015419e-02 9.79998458e-01]
 [9.93102387e-01 6.89761290e-03]
 [9.56981968e-01 4.30180316e-02]
 [5.72278636e-03 9.94277214e-01]
 [9.92190573e-01 7.80942689e-03]
 [1.58064219e-07 9.99999842e-01]
 [3.60532033e-08 9.99999964e-01]
 [9.95596227e-01 4.40377288e-03]
 [3.15258641e-09 9.99999997e-01]
 [1.12528486e-02 9.88747151e-01]
 [9.83080769e-01 1.69192310e-02]
 [2.74444707e-07 9.99999726e-01]
 [2.89329380e-03 9.97106706e-01]
 [9.80308961e-01 1.96910385e-02]
 [9.96990957e-01 3.00904338e-03]
 [5.30379819e-03 9.94696202e-01]
 [9.84957314e-01 1.50426858e-02]
 [9.78392024e-01 2.16079763e-02]
 [9.94370016e-01 5.62998419e-03]
 [3.61427656e-07 9.99999639e-01]
 [9.91189377e-01 8.81062271e-03]
 [9.86734444e-01 1.32655556e-02]
 [9.88097009e-01 1.19029911e-02]
 [4.76841673e-06 9.99995232e-01]
 [1.24736335e-06 9.99998753e-01]
 [5.12868121e-03 9.94871319e-01]
 [1.29156384e-08 9.99999987e-01]
 [3.86408932e-01 6.13591068e-01]
 [9.58975079e-01 4.10249215e-02]
 [9.96932382e-01 3.06761777e-03]
 [9.90195367e-01 9.80463280e-03]
 [9.98233335e-01 1.76666544e-03]
 [1.97957825e-02 9.80204217e-01]
 [9.86085708e-01 1.39142924e-02]
 [9.25834917e-03 9.90741651e-01]
 [9.96119811e-01 3.88018894e-03]
 [9.91346570e-01 8.65343021e-03]
 [9.65790884e-01 3.42091165e-02]
 [3.69866750e-06 9.99996301e-01]
 [9.94881579e-01 5.11842141e-03]
 [9.95937053e-01 4.06294705e-03]
 [9.87279955e-01 1.27200446e-02]
 [9.97007863e-01 2.99213724e-03]
 [9.96262161e-01 3.73783870e-03]
 [6.10652421e-06 9.99993893e-01]
 [2.31850041e-02 9.76814996e-01]
 [1.45704414e-07 9.99999854e-01]
 [9.97964880e-01 2.03512037e-03]
 [9.95333938e-01 4.66606228e-03]
 [9.63637466e-01 3.63625338e-02]
 [9.95833599e-01 4.16640128e-03]
 [2.23963779e-01 7.76036221e-01]
 [9.93119984e-01 6.88001558e-03]
 [2.75363732e-02 9.72463627e-01]
 [9.96742282e-01 3.25771827e-03]
 [9.96546810e-01 3.45318975e-03]
 [9.97679979e-01 2.32002110e-03]
 [9.98310381e-01 1.68961883e-03]
 [4.39466827e-03 9.95605332e-01]
 [2.25268280e-06 9.99997747e-01]
 [7.32846114e-03 9.92671539e-01]
 [3.44952212e-06 9.99996550e-01]
 [9.96347779e-01 3.65222052e-03]
 [9.64038517e-01 3.59614831e-02]
 [9.95314285e-01 4.68571471e-03]
 [9.97227447e-01 2.77255314e-03]
 [2.68180843e-03 9.97318192e-01]
 [9.95928734e-01 4.07126619e-03]
 [9.92097805e-01 7.90219462e-03]
 [9.95039480e-01 4.96051992e-03]
 [9.87014693e-01 1.29853075e-02]
 [9.87483959e-01 1.25160407e-02]
 [9.78700319e-01 2.12996814e-02]
 [9.25667697e-07 9.99999074e-01]
 [9.81729877e-01 1.82701227e-02]
 [9.14736493e-01 8.52635067e-02]
 [9.95121887e-01 4.87811349e-03]
 [9.97071413e-01 2.92858684e-03]
 [9.66837789e-01 3.31622112e-02]
 [9.84878505e-01 1.51214952e-02]
 [9.98197189e-01 1.80281076e-03]
 [3.79041093e-06 9.99996210e-01]
 [9.55108885e-01 4.48911150e-02]
 [1.36884101e-06 9.99998631e-01]
 [3.21571089e-07 9.99999678e-01]
 [1.06464467e-07 9.99999894e-01]
 [9.89780941e-01 1.02190585e-02]
 [6.35155027e-08 9.99999936e-01]
 [3.20799022e-03 9.96792010e-01]
 [1.56586861e-01 8.43413139e-01]
 [6.17963823e-03 9.93820362e-01]
 [9.96657820e-01 3.34217999e-03]
 [9.81121520e-01 1.88784798e-02]
 [6.85128629e-06 9.99993149e-01]
 [9.94358263e-01 5.64173737e-03]
 [9.96429128e-01 3.57087245e-03]
 [1.14445972e-02 9.88555403e-01]
 [9.93438459e-01 6.56154073e-03]
 [1.18205816e-05 9.99988179e-01]
 [1.84352630e-01 8.15647370e-01]
 [1.38439469e-02 9.86156053e-01]
 [9.67690352e-01 3.23096482e-02]
 [5.57055269e-03 9.94429447e-01]
 [1.86313713e-07 9.99999814e-01]
 [9.91459743e-01 8.54025733e-03]
 [9.93617869e-01 6.38213059e-03]
 [9.95538902e-01 4.46109756e-03]
 [9.96684090e-01 3.31591048e-03]
 [7.92579374e-03 9.92074206e-01]
 [9.95996151e-01 4.00384861e-03]
 [2.32776521e-02 9.76722348e-01]
 [1.78824084e-06 9.99998212e-01]
 [3.52360136e-06 9.99996476e-01]
 [4.65144810e-03 9.95348552e-01]
 [9.98799817e-01 1.20018275e-03]
 [9.92622781e-01 7.37721917e-03]
 [3.22501829e-02 9.67749817e-01]
 [9.96953898e-01 3.04610237e-03]
 [1.11658241e-02 9.88834176e-01]
 [9.87926689e-01 1.20733106e-02]
 [6.50105352e-02 9.34989465e-01]
 [9.33720504e-01 6.62794963e-02]
 [9.71438539e-01 2.85614614e-02]
 [3.91468422e-03 9.96085316e-01]
 [9.95552083e-01 4.44791652e-03]]

In [49]:
print(type(probs))

<class 'numpy.ndarray'>

In [50]:
print(probs.ndim)

2

In [111]:
probsdf = pd.DataFrame(probs, columns=["0", "1"])

In [52]:
probsdf.to_csv("svm_1.csv")

GETTING THE CSV OUTPUT FOR SUBMITTED FORMAT

In [ ]:
#1. sc on Test (transform only)
#2. pca on Test (transform only)
#3. run model on Test (predict only)
#4. run predict_proba on predictions
#5. somehow only select high probability column
#6. export everything to csv's

In [56]:
# trying #5 first to make my life easier
probsdf.head()

              0         1
0  5.728762e-08  1.000000
1  9.943784e-01  0.005622
2  9.941647e-01  0.005835
3  9.930476e-01  0.006952
4  9.890405e-01  0.010960

In [60]:
probsdf['max_val'] = probsdf[['0', '1']].max(axis=1)

In [61]:
probsdf.head()

              0         1   max_val
0  5.728762e-08  1.000000  1.000000
1  9.943784e-01  0.005622  0.994378
2  9.941647e-01  0.005835  0.994165
3  9.930476e-01  0.006952  0.993048
4  9.890405e-01  0.010960  0.989040

In [68]:
probmax = probsdf['max_val']

In [71]:
probmax.head()

0    1.000000
1    0.994378
2    0.994165
3    0.993048
4    0.989040
Name: max_val, dtype: float64

In [74]:
probmax2 = pd.DataFrame(probmax)

In [75]:
probmax2.head()

    max_val
0  1.000000
1  0.994378
2  0.994165
3  0.993048
4  0.989040

In [86]:
#great that worked!, now select the 'max_val' column and append to your prediction dataframe/csv
preddf = pd.DataFrame(y_pred, columns=["pred"])

In [87]:
preddf.head(15)

    pred
0      1
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      1
10     1
11     1
12     0
13     1
14     1

In [88]:
#now combine probmax2 and add it to preddf
final1 = pd.concat([preddf, probmax2], axis=1)

In [89]:
final1.head(15)

    pred   max_val
0      1  1.000000
1      0  0.994378
2      0  0.994165
3      0  0.993048
4      0  0.989040
5      0  0.992762
6      0  0.986052
7      0  0.929118
8      0  0.974302
9      1  1.000000
10     1  0.760151
11     1  0.993793
12     0  0.977569
13     1  0.977353
14     1  0.999989

In [90]:
final1.to_csv("final.csv")

## NOW RUN ON SUPPLIED TEST

In [272]:
df = pd.read_csv('Test.csv')

In [273]:
df1 = df.drop(['lon', 'lat'], axis=1)

In [274]:
df1.dtypes

ID              str
VH_01       float64
VV_01       float64
blue_01       int64
green_01      int64
             ...
re2_12        int64
re3_12        int64
red_12        int64
swir1_12      int64
swir2_12      int64
Length: 145, dtype: object

In [275]:
#ok, it only has ID, no problem
cols = df1.columns.difference(['ID'])

In [276]:
df1[cols] = sc.transform(df1[cols])

In [277]:
cols2 = df1.columns.difference(['ID'])

In [278]:
components_test = pca.transform(df1[cols2])

In [279]:
y_pred = clf.predict(components_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [280]:
length = len(y_pred)
print(length)  # Output: 858 is correct for 'Test.csv'

858

In [281]:
preddf = pd.DataFrame(y_pred, columns=["pred"])

In [282]:
preddf.head()

   pred
0     0
1     0
2     0
3     0
4     0

In [283]:
probs = clf.predict_proba(components_test)

In [284]:
print(probs)

[[9.96106685e-01 3.89331503e-03]
 [9.81550319e-01 1.84496815e-02]
 [9.55612500e-01 4.43874996e-02]
 ...
 [1.73839514e-05 9.99982616e-01]
 [3.53792181e-03 9.96462078e-01]
 [2.17251771e-02 9.78274823e-01]]

In [285]:
length = len(probs)
print(length)  # Output: 858 is correct for 'Test.csv'

858

In [286]:
print(probs.ndim)

2

In [287]:
probsdf = pd.DataFrame(probs, columns=["0", "1"])

In [288]:
probsdf.head()

          0         1
0  0.996107  0.003893
1  0.981550  0.018450
2  0.955613  0.044387
3  0.996102  0.003898
4  0.957029  0.042971

In [289]:
probsdf['max_val'] = probsdf[['0', '1']].max(axis=1)
probsdf.head()

          0         1   max_val
0  0.996107  0.003893  0.996107
1  0.981550  0.018450  0.981550
2  0.955613  0.044387  0.955613
3  0.996102  0.003898  0.996102
4  0.957029  0.042971  0.957029

In [290]:
probmax = probsdf['max_val']

In [291]:
probmax2 = pd.DataFrame(probmax)

In [292]:
probmax2.head()

    max_val
0  0.996107
1  0.981550
2  0.955613
3  0.996102
4  0.957029

In [296]:
#now combine probmax2 and add it to preddf
model4 = pd.concat([preddf, probmax2], axis=1)

In [297]:
model4.head(15)

    pred   max_val
0      0  0.996107
1      0  0.981550
2      0  0.955613
3      0  0.996102
4      0  0.957029
5      0  0.871608
6      0  0.833012
7      0  0.666146
8      0  0.986956
9      0  0.942657
10     0  0.990562
11     0  0.989583
12     0  0.988212
13     0  0.997859
14     0  0.986783

In [298]:
model4.to_csv("model4_svm_alltrain_pca20.csv")

## TRY A NEURAL NETWORK

In [329]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score
from sklearn.neural_network import MLPClassifier

In [330]:
mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)

In [331]:
mlp.fit(components_train, y_train)

MLPClassifier(hidden_layer_sizes=(8, 8, 8), max_iter=500)

In [332]:
y_pred = mlp.predict(components_train)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1])

In [333]:
accuracy = accuracy_score(y_train, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 1.0

In [334]:
mlp.score(components_train, y_train)

1.0

RUN ON SUPPLIED TEST

In [335]:
df = pd.read_csv('Test.csv')
df1 = df.drop(['lon', 'lat'], axis=1)

In [336]:
cols = df1.columns.difference(['ID'])

In [337]:
df1[cols] = sc.transform(df1[cols])

In [338]:
cols2 = df1.columns.difference(['ID'])

In [339]:
components_test = pca.transform(df1[cols2])

In [340]:
y_pred = mlp.predict(components_test)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [341]:
length = len(y_pred)
print(length)  # Output: 858 is correct for 'Test.csv'

858

In [342]:
preddf = pd.DataFrame(y_pred, columns=["pred"])

In [343]:
probs = mlp.predict_proba(components_test)

In [344]:
length = len(probs)
print(length)  # Output: 858 is correct for 'Test.csv'

858

In [345]:
probsdf = pd.DataFrame(probs, columns=["0", "1"])

In [346]:
probsdf['max_val'] = probsdf[['0', '1']].max(axis=1)
probsdf.head()

          0             1   max_val
0  0.999996  3.838238e-06  0.999996
1  1.000000  2.160388e-07  1.000000
2  0.968529  3.147107e-02  0.968529
3  0.999998  1.702893e-06  0.999998
4  0.806157  1.938428e-01  0.806157

In [347]:
probmax = probsdf['max_val']

In [348]:
probmax2 = pd.DataFrame(probmax)

In [349]:
probmax2.head()

    max_val
0  0.999996
1  1.000000
2  0.968529
3  0.999998
4  0.806157

In [352]:
#now combine probmax2 and add it to preddf
model5 = pd.concat([preddf, probmax2], axis=1)

In [353]:
model5.head(15)

    pred   max_val
0      0  0.999996
1      0  1.000000
2      0  0.968529
3      0  0.999998
4      0  0.806157
5      0  0.976208
6      1  0.994531
7      1  0.996912
8      0  0.999996
9      0  0.983804
10     0  0.999931
11     0  1.000000
12     0  0.999999
13     0  0.999817
14     0  0.999814

In [354]:
model5.to_csv("model5_mlpnn_alltrain_pca20.csv")